default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: dep_test_development  #アプリケーション名_developmentとなる

test:
  <<: *default
  database: dep_test_test  #アプリケーション名_testとなる

production:
  <<: *default
  database: dep_test_production  #アプリケーション名_productionとなる
  username: root            #rootに変更
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock